export { ArticlePageDetailsAsync as ArticlePageDetails } from './ui/page/index.async'
export { StateSchemaArticleDetailsComments } from './model/types/state-schema-article-details'
export { StateSchemaArticleDetailsRecommendations } from './model/types/state-schema-recommendations'
export { StateSchemaArticleDetailsPage } from './model/types/state-schema-page'
export { articleDetailsPageReducer } from './model/slice/article-details-reducer'
